project:
  type: website

website:
  title: ""
  site-url: https://niccrane.com
  navbar:
    right:
      - text: Home
        file: index.qmd
      - text: About
        file: about.qmd
      - text: Workshops
        file: workshops.qmd
      - text: Past Work
        file: projects.qmd
      - text: Talks
        file: talks.qmd
      - text: Blog
        file: blog.qmd
      - icon: rss
        href: blog.xml
  google-analytics: "G-SJ58WZL69W"
format:
  html:
    theme: [sandstone, custom.scss]

editor: visual

