project:
  type: website

website:
  title: Dr Nic Crane
  site-url: https://niccrane.com
  navbar:
    right:
      - text: Home
        file: index.qmd
      - text: About
        file: about.qmd
      - text: Past Work
        file: projects.qmd
      - text: Talks & Workshops
        file: talks.qmd
      - text: Blog
        file: blog.qmd
      - icon: rss
        href: blog.xml
  google-analytics: "G-SJ58WZL69W"
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

